"""
fpga.py -- FPGA targeting: estimation, synthesis attributes, and build scripts.

While the Verilog generated by w2s is already synthesizable on FPGAs,
this module provides FPGA-specific optimizations and tooling:

- FPGA resource estimation (LUTs, BRAMs, DSP slices)
- Synthesis attribute hints for block RAM and DSP inference
- Build script generation for open-source FPGA toolchains
- Pin constraint file templates for popular boards
"""

import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Dict, Optional

import numpy as np

from w2s.core import ComputeGraph, Operation, OpType


# ---------------------------------------------------------------------------
#  FPGA device definitions
# ---------------------------------------------------------------------------

@dataclass
class FPGADevice:
    """FPGA device resource specifications."""
    name: str
    family: str
    lut4s: int           # total LUT4 equivalents
    ffs: int             # total flip-flops
    bram_18k: int        # 18Kbit block RAMs
    bram_bits: int       # total BRAM bits
    dsp_slices: int      # DSP multiplier blocks
    dsp_width: int       # native DSP multiplier width (e.g., 18 for DSP48)
    max_freq_mhz: int    # typical max clock frequency
    package: str = ""    # device package (e.g., "sg48", "CABGA381")


# Common open-source FPGA targets
ICE40_UP5K = FPGADevice(
    name="iCE40UP5K", family="ice40",
    lut4s=5280, ffs=5280, bram_18k=0,
    bram_bits=120 * 1024,  # 30 x 4Kbit EBR blocks
    dsp_slices=0, dsp_width=0,
    max_freq_mhz=48,
    package="sg48",
)

ICE40_HX8K = FPGADevice(
    name="iCE40HX8K", family="ice40",
    lut4s=7680, ffs=7680, bram_18k=0,
    bram_bits=32 * 4096,  # 32 x 4Kbit block RAMs
    dsp_slices=0, dsp_width=0,
    max_freq_mhz=100,
    package="ct256",
)

ECP5_25K = FPGADevice(
    name="ECP5-25K", family="ecp5",
    lut4s=24576, ffs=24576, bram_18k=56,
    bram_bits=56 * 18 * 1024,
    dsp_slices=28, dsp_width=18,
    max_freq_mhz=200,
    package="CABGA381",
)

ECP5_85K = FPGADevice(
    name="ECP5-85K", family="ecp5",
    lut4s=83640, ffs=83640, bram_18k=208,
    bram_bits=208 * 18 * 1024,
    dsp_slices=156, dsp_width=18,
    max_freq_mhz=200,
    package="CABGA554",
)

DEVICES = {
    "ice40up5k": ICE40_UP5K,
    "ice40hx8k": ICE40_HX8K,
    "ecp5-25k": ECP5_25K,
    "ecp5-85k": ECP5_85K,
}


# ---------------------------------------------------------------------------
#  FPGA resource estimation
# ---------------------------------------------------------------------------

@dataclass
class FPGAEstimate:
    """FPGA-specific resource estimates."""
    device: FPGADevice
    mode: str
    lut4s_used: int
    ffs_used: int
    bram_bits_used: int
    bram_blocks_used: int
    dsp_slices_used: int
    fits: bool
    utilization_lut: float
    utilization_bram: float
    utilization_dsp: float
    warnings: List[str] = field(default_factory=list)
    _breakdown: Dict[str, int] = field(default_factory=dict, repr=False)

    def __str__(self) -> str:
        lines = []
        lines.append(f"=== FPGA Estimate: {self.device.name} ({self.mode} mode) ===")
        lines.append(f"LUT4s:       {self.lut4s_used:,} / {self.device.lut4s:,} "
                     f"({self.utilization_lut:.0%})")
        lines.append(f"Flip-flops:  {self.ffs_used:,} / {self.device.ffs:,}")
        lines.append(f"BRAM bits:   {self.bram_bits_used:,} / {self.device.bram_bits:,} "
                     f"({self.utilization_bram:.0%})")
        if self.device.dsp_slices > 0:
            lines.append(f"DSP slices:  {self.dsp_slices_used:,} / {self.device.dsp_slices:,} "
                         f"({self.utilization_dsp:.0%})")
        else:
            lines.append(f"DSP slices:  N/A (device has no hard multipliers)")

        if self.fits:
            lines.append(f"Status:      FITS")
        else:
            over = []
            if self.lut4s_used > self.device.lut4s:
                over.append("LUTs")
            if self.bram_bits_used > self.device.bram_bits:
                over.append("BRAM")
            if self.dsp_slices_used > self.device.dsp_slices and self.device.dsp_slices > 0:
                over.append("DSP")
            lines.append(f"Status:      DOES NOT FIT (exceeds: {', '.join(over)})")

        if self.warnings:
            lines.append("")
            for w in self.warnings:
                lines.append(f"  - {w}")

        return "\n".join(lines)


def estimate_fpga(
    graph: ComputeGraph,
    device: FPGADevice = None,
    mode: str = "combinational",
) -> FPGAEstimate:
    """
    Estimate FPGA resource usage for a compiled design.

    In sequential mode, weights go to BRAM and a single DSP handles MAC.
    In combinational mode, weights become LUT logic with optional DSP for
    large multipliers.
    """
    if mode not in ("combinational", "sequential"):
        raise ValueError(f"Unknown mode '{mode}'; expected 'combinational' or 'sequential'")

    if device is None:
        device = ICE40_UP5K

    bits = graph.quant_config.bits
    ops = graph.topological_order()
    warnings = []

    # Count parameters
    total_params = 0
    total_multiplies = 0
    for op in ops:
        weights = op.q_weights if op.q_weights else op.weights
        for w in weights.values():
            total_params += int(np.prod(w.shape))
        if op.op_type in (OpType.DENSE, OpType.CONV1D, OpType.CONV2D):
            w = weights.get('weight')
            if w is not None:
                total_multiplies += int(np.count_nonzero(w))

    rom_bits = total_params * bits

    if mode == "sequential":
        return _estimate_fpga_sequential(
            graph, device, ops, total_params, total_multiplies,
            rom_bits, bits, warnings)
    else:
        return _estimate_fpga_combinational(
            graph, device, ops, total_params, total_multiplies,
            rom_bits, bits, warnings)


def _estimate_fpga_sequential(graph, device, ops, total_params,
                               total_multiplies, rom_bits, bits, warnings):
    """Sequential mode: weights in BRAM, single MAC in DSP or LUTs."""
    # BRAM usage: all weights stored in block RAM
    bram_bits_used = rom_bits

    # MAC engine: 1 DSP slice if device supports it, otherwise LUTs
    if device.dsp_slices > 0 and bits <= device.dsp_width:
        dsp_used = 1
        mac_luts = 50  # control logic only
    else:
        dsp_used = 0
        mac_luts = 200 + 32  # multiplier + accumulator in LUTs

    # Control logic + state machine + buffers
    control_luts = 80
    # Buffer for largest intermediate activation
    max_buf = 0
    for op in ops:
        weights = op.q_weights if op.q_weights else op.weights
        w = weights.get('weight')
        if w is not None:
            max_buf = max(max_buf, w.shape[0])
    buffer_ffs = max_buf * bits + 80  # activation buffer + state regs

    lut4s_used = mac_luts + control_luts
    # If BRAM can't hold all weights, spill to LUTs
    if bram_bits_used > device.bram_bits:
        spill_bits = bram_bits_used - device.bram_bits
        lut4s_used += spill_bits // 4  # ~4 bits per LUT4 for ROM
        warnings.append(f"Weights exceed BRAM ({rom_bits:,} bits > "
                       f"{device.bram_bits:,} bits). "
                       f"{spill_bits:,} bits spill to LUT fabric.")
    bram_blocks = math.ceil(bram_bits_used / 18432) if device.bram_18k > 0 else 0

    fits = (lut4s_used <= device.lut4s and
            dsp_used <= device.dsp_slices and
            bram_bits_used <= device.bram_bits)

    return FPGAEstimate(
        device=device,
        mode="sequential",
        lut4s_used=lut4s_used,
        ffs_used=buffer_ffs,
        bram_bits_used=min(bram_bits_used, device.bram_bits),
        bram_blocks_used=bram_blocks,
        dsp_slices_used=dsp_used,
        fits=fits,
        utilization_lut=lut4s_used / device.lut4s if device.lut4s else 0,
        utilization_bram=bram_bits_used / device.bram_bits if device.bram_bits else 0,
        utilization_dsp=dsp_used / device.dsp_slices if device.dsp_slices else 0,
        warnings=warnings,
    )


def _estimate_fpga_combinational(graph, device, ops, total_params,
                                  total_multiplies, rom_bits, bits, warnings):
    """Combinational mode: weights as LUT logic, optional DSP for multipliers."""
    bit_scale = bits / 8.0

    # Each constant multiply: ~6 LUT4s per bit of the constant
    # (shift-add decomposition maps to LUT chains)
    luts_per_mul = int(24 * bit_scale)
    luts_per_add = int(8 * bit_scale)

    mul_luts = total_multiplies * luts_per_mul
    add_luts = 0

    # Count requant and saturation
    n_neurons = 0
    for op in ops:
        weights = op.q_weights if op.q_weights else op.weights
        w = weights.get('weight')
        if w is not None:
            n_neurons += w.shape[0]
            add_luts += max(int(np.count_nonzero(w)) - w.shape[0], 0) * luts_per_add

    requant_luts = n_neurons * 64
    sat_luts = n_neurons * 8

    # DSP offloading: if device has DSPs, use them for the largest multipliers
    dsp_used = 0
    dsp_savings = 0
    if device.dsp_slices > 0 and bits <= device.dsp_width:
        # Each DSP can handle one full multiply.  Use DSPs for requantization
        # multipliers (one per neuron output) since those are the widest.
        dsp_used = min(n_neurons, device.dsp_slices)
        dsp_savings = dsp_used * 64  # each DSP replaces ~64 LUTs of requant logic
        requant_luts = max(0, requant_luts - dsp_savings)

    lut4s_used = mul_luts + add_luts + requant_luts + sat_luts

    fits = (lut4s_used <= device.lut4s and
            dsp_used <= device.dsp_slices)

    if not fits:
        warnings.append(
            f"Design needs ~{lut4s_used:,} LUT4s but device has {device.lut4s:,}. "
            f"Consider sequential mode or a larger FPGA.")

    return FPGAEstimate(
        device=device,
        mode="combinational",
        lut4s_used=lut4s_used,
        ffs_used=0,  # combinational: no FFs
        bram_bits_used=0,  # combinational: weights in LUTs
        bram_blocks_used=0,
        dsp_slices_used=dsp_used,
        fits=fits,
        utilization_lut=lut4s_used / device.lut4s if device.lut4s else 0,
        utilization_bram=0,
        utilization_dsp=dsp_used / device.dsp_slices if device.dsp_slices else 0,
        warnings=warnings,
        _breakdown={
            "mul_luts": mul_luts,
            "add_luts": add_luts,
            "requant_luts": requant_luts,
            "sat_luts": sat_luts,
            "dsp_savings": dsp_savings,
        },
    )


# ---------------------------------------------------------------------------
#  Build script generation
# ---------------------------------------------------------------------------

def generate_build_script(
    graph: ComputeGraph,
    device: FPGADevice = None,
    output_dir: str = ".",
    mode: str = "combinational",
    pcf_file: Optional[str] = None,
) -> str:
    """
    Generate a Makefile for open-source FPGA synthesis.

    Supports:
      - iCE40 family: Yosys -> nextpnr-ice40 -> icepack -> iceprog
      - ECP5 family:  Yosys -> nextpnr-ecp5 -> ecppack -> openFPGALoader
    """
    if device is None:
        device = ICE40_UP5K

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    if mode == "sequential":
        top_module = f"{graph.name}_seq"
        verilog_files = [f"{graph.name}_seq.v"]
    else:
        top_module = graph.name
        verilog_files = [f"{graph.name}.v"]

    vfiles = " ".join(verilog_files)

    lines = []
    lines.append(f"# Makefile for {graph.name} — generated by weights2silicon (w2s)")
    lines.append(f"# Target: {device.name} ({device.family})")
    lines.append(f"# Mode: {mode}")
    lines.append(f"")
    lines.append(f"TOP      = {top_module}")
    lines.append(f"VERILOG  = {vfiles}")

    if pcf_file:
        lines.append(f"PCF      = {pcf_file}")
    elif device.family == "ecp5":
        lines.append(f"PCF      = pins.lpf")
    else:
        lines.append(f"PCF      = pins.pcf")

    lines.append(f"")

    if device.family == "ice40":
        pkg = device.package or "sg48"
        if "hx8k" in device.name.lower():
            dev_flag = "hx8k"
        elif "up5k" in device.name.lower():
            dev_flag = "up5k"
        else:
            dev_flag = device.name.lower().replace("ice40", "")

        lines.append(f"# iCE40 toolchain: Yosys + nextpnr-ice40 + icepack")
        lines.append(f"")
        lines.append(f"all: $(TOP).bin")
        lines.append(f"")
        lines.append(f"# Synthesis")
        lines.append(f"$(TOP).json: $(VERILOG)")
        lines.append(f"\tyosys -p 'synth_ice40 -top $(TOP) -json $@' $(VERILOG)")
        lines.append(f"")
        lines.append(f"# Place and route")
        lines.append(f"$(TOP).asc: $(TOP).json $(PCF)")
        lines.append(f"\tnextpnr-ice40 --{dev_flag} --package {pkg} "
                     f"--json $(TOP).json --pcf $(PCF) --asc $@")
        lines.append(f"")
        lines.append(f"# Bitstream")
        lines.append(f"$(TOP).bin: $(TOP).asc")
        lines.append(f"\ticepack $(TOP).asc $@")
        lines.append(f"")
        lines.append(f"# Program")
        lines.append(f"prog: $(TOP).bin")
        lines.append(f"\ticeprog $(TOP).bin")
        lines.append(f"")
        lines.append(f"# Timing report")
        lines.append(f"timing: $(TOP).asc")
        lines.append(f"\ticetime -d {dev_flag} $(TOP).asc")
        lines.append(f"")

    elif device.family == "ecp5":
        if "25k" in device.name.lower():
            dev_flag = "25k"
        elif "85k" in device.name.lower():
            dev_flag = "85k"
        else:
            dev_flag = "45k"

        lines.append(f"# ECP5 toolchain: Yosys + nextpnr-ecp5 + ecppack")
        lines.append(f"")
        lines.append(f"all: $(TOP).bit")
        lines.append(f"")
        lines.append(f"# Synthesis")
        lines.append(f"$(TOP).json: $(VERILOG)")
        lines.append(f"\tyosys -p 'synth_ecp5 -top $(TOP) -json $@' $(VERILOG)")
        lines.append(f"")
        lines.append(f"# Place and route")
        lines.append(f"$(TOP).config: $(TOP).json $(PCF)")
        lines.append(f"\tnextpnr-ecp5 --{dev_flag} --package {device.package or 'CABGA381'} "
                     f"--json $(TOP).json --lpf $(PCF) --textcfg $@")
        lines.append(f"")
        lines.append(f"# Bitstream")
        lines.append(f"$(TOP).bit: $(TOP).config")
        lines.append(f"\tecppack --compress $< $@")
        lines.append(f"")
        lines.append(f"# Program")
        lines.append(f"prog: $(TOP).bit")
        lines.append(f"\topenFPGALoader $(TOP).bit")
        lines.append(f"")

    # Common targets
    lines.append(f"# Resource usage report (synthesis only)")
    lines.append(f"report: $(TOP).json")
    lines.append(f"\t@echo 'See yosys synthesis log for resource usage'")
    lines.append(f"")
    lines.append(f"# Simulation (Icarus Verilog)")
    lines.append(f"sim: $(VERILOG) $(TOP)_tb.v")
    lines.append(f"\tiverilog -o $(TOP)_sim $(VERILOG) $(TOP)_tb.v")
    lines.append(f"\tvvp $(TOP)_sim")
    lines.append(f"")
    lines.append(f"clean:")
    lines.append(f"\trm -f $(TOP).json $(TOP).asc $(TOP).config "
                 f"$(TOP).bin $(TOP).bit $(TOP)_sim *.vcd")
    lines.append(f"")
    lines.append(f".PHONY: all prog timing report sim clean")

    mk_path = out / "Makefile"
    mk_path.write_text("\n".join(lines), encoding="utf-8")
    return str(mk_path)


# ---------------------------------------------------------------------------
#  Pin constraint templates
# ---------------------------------------------------------------------------

def generate_constraints(
    graph: ComputeGraph,
    device: FPGADevice = None,
    output_dir: str = ".",
    mode: str = "combinational",
) -> str:
    """
    Generate a pin constraint template file.

    Creates a .pcf (iCE40) or .lpf (ECP5) file with placeholder pin
    assignments for the design's I/O signals.
    """
    if device is None:
        device = ICE40_UP5K

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    bits = graph.quant_config.bits

    lines = []
    lines.append(f"# Pin constraints for {graph.name}")
    lines.append(f"# Target: {device.name}")
    lines.append(f"# Generated by weights2silicon (w2s)")
    lines.append(f"#")
    lines.append(f"# IMPORTANT: Replace pin numbers with your actual board pinout!")
    lines.append(f"#")
    lines.append(f"")

    if mode == "sequential":
        if device.family == "ice40":
            lines.append(f"# Clock and reset")
            lines.append(f"set_io clk        35")
            lines.append(f"set_io rst_n      2")
            lines.append(f"")
            lines.append(f"# Serial data interface")
            for i in range(bits):
                lines.append(f"set_io data_in[{i}]  {10 + i}  # REPLACE")
            lines.append(f"set_io data_valid  {10 + bits}  # REPLACE")
            lines.append(f"")
            for i in range(bits):
                lines.append(f"set_io data_out[{i}] {20 + i}  # REPLACE")
            lines.append(f"set_io out_valid   {20 + bits}  # REPLACE")
            lines.append(f"set_io done        {20 + bits + 1}  # REPLACE")
            lines.append(f"set_io ready       {20 + bits + 2}  # REPLACE")

        elif device.family == "ecp5":
            lines.append(f"LOCATE COMP \"clk\"        SITE \"P6\";")
            lines.append(f"LOCATE COMP \"rst_n\"      SITE \"T1\";")
            lines.append(f"IOBUF PORT \"clk\" IO_TYPE=LVCMOS33;")
            lines.append(f"IOBUF PORT \"rst_n\" IO_TYPE=LVCMOS33;")
            lines.append(f"")
            lines.append(f"# Serial data interface — REPLACE pin sites")
            for i in range(bits):
                lines.append(f"LOCATE COMP \"data_in[{i}]\" SITE \"REPLACE\";")
            lines.append(f"LOCATE COMP \"data_valid\" SITE \"REPLACE\";")
            for i in range(bits):
                lines.append(f"LOCATE COMP \"data_out[{i}]\" SITE \"REPLACE\";")
            lines.append(f"LOCATE COMP \"out_valid\" SITE \"REPLACE\";")
            lines.append(f"LOCATE COMP \"done\" SITE \"REPLACE\";")
            lines.append(f"LOCATE COMP \"ready\" SITE \"REPLACE\";")

    else:  # combinational mode: parallel I/O ports
        # Build list of input wire names from graph
        input_wires = []
        for inp_name in graph.input_names:
            shape = graph.input_shapes.get(inp_name, (1,))
            numel = 1
            for s in shape:
                numel *= s
            for i in range(numel):
                input_wires.append(f"{inp_name}_{i}")

        # Build list of output wire names from graph
        output_wires = []
        for out_name in graph.output_names:
            # Mirror the naming convention from graph.py
            # For single output: out_0, out_1, ...
            # For multiple outputs: out_{name}_0, out_{name}_1, ...
            # Use a reasonable default count based on graph info
            multi = len(graph.output_names) > 1
            prefix = f"out_{out_name}" if multi else "out"
            # We don't know the exact output width here, so emit one
            # placeholder per output name; users extend as needed.
            output_wires.append(f"{prefix}_0")

        if device.family == "ice40":
            lines.append(f"# Combinational inputs")
            for idx, w in enumerate(input_wires):
                lines.append(f"set_io {w}  {10 + idx}  # REPLACE")
            lines.append(f"")
            lines.append(f"# Combinational outputs")
            for idx, w in enumerate(output_wires):
                lines.append(f"set_io {w}  {30 + idx}  # REPLACE")

        elif device.family == "ecp5":
            lines.append(f"# Combinational inputs — REPLACE pin sites")
            for w in input_wires:
                lines.append(f"LOCATE COMP \"{w}\" SITE \"REPLACE\";")
            lines.append(f"")
            lines.append(f"# Combinational outputs — REPLACE pin sites")
            for w in output_wires:
                lines.append(f"LOCATE COMP \"{w}\" SITE \"REPLACE\";")

    ext = "pcf" if device.family == "ice40" else "lpf"
    pcf_path = out / f"pins.{ext}"
    pcf_path.write_text("\n".join(lines), encoding="utf-8")
    return str(pcf_path)
