"""
wrapper.py — Sequential I/O wrapper and Tiny Tapeout interface.

The combinational core generated by graph.py has all inputs/outputs
as parallel wires. For real deployment, you need serial I/O:
  - Feed inputs one value at a time over an 8-bit bus
  - Read outputs one value at a time

This module generates a wrapper state machine around the combinational core.
"""

from pathlib import Path
from typing import List, Tuple
import math

from w2s.core import ComputeGraph
from w2s import emit


def generate_serial_wrapper(
    graph: ComputeGraph,
    output_dir: str = ".",
) -> str:
    """
    Generate a sequential wrapper with serial I/O around the combinational core.

    Interface:
        clk         — clock
        rst_n       — active-low reset
        data_in[7:0] — serial input bus
        data_valid  — pulse high for one cycle per input value
        start       — pulse high to begin computation (after loading all inputs)
        data_out[7:0] — serial output bus
        out_valid   — high when data_out contains valid result
        done        — high when all outputs have been read
        ready       — high when idle, ready for new inputs
    """
    out = Path(output_dir)
    bits = graph.quant_config.bits

    # Compute total input/output counts
    n_in = 0
    for inp_name in graph.input_names:
        shape = graph.input_shapes.get(inp_name, (1,))
        numel = 1
        for s in shape:
            numel *= s
        n_in += numel

    n_out = 0
    # Estimate from operations (output shapes)
    for op in reversed(graph.operations):
        if any(o in graph.output_names for o in op.outputs):
            if op.op_type.value == "dense" and 'weight' in op.q_weights:
                n_out += op.q_weights['weight'].shape[0]
            else:
                n_out += 1  # fallback estimate
    n_out = max(n_out, 1)

    addr_bits_in = max(math.ceil(math.log2(max(n_in, 2))), 1)
    addr_bits_out = max(math.ceil(math.log2(max(n_out, 2))), 1)

    L: List[str] = []

    def e(s=""):
        L.append(s)

    core_name = graph.name
    wrapper_name = f"{graph.name}_serial"

    e(f"// {'=' * 75}")
    e(f"// {wrapper_name} — Serial I/O wrapper for {core_name}")
    e(f"// Generated by weights2silicon (w2s)")
    e(f"//")
    e(f"// Feed {n_in} input values one-at-a-time via data_in + data_valid,")
    e(f"// then read {n_out} output values one-at-a-time from data_out + out_valid.")
    e(f"// {'=' * 75}")
    e()
    e(f"module {wrapper_name} (")
    e(f"    input  wire       clk,")
    e(f"    input  wire       rst_n,")
    e(f"    input  wire [{bits-1}:0] data_in,")
    e(f"    input  wire       data_valid,")
    e(f"    output reg  [{bits-1}:0] data_out,")
    e(f"    output reg        out_valid,")
    e(f"    output reg        done,")
    e(f"    output wire       ready")
    e(f");")
    e()

    # State machine
    e(f"    localparam IDLE    = 2'd0;")
    e(f"    localparam LOADING = 2'd1;")
    e(f"    localparam COMPUTE = 2'd2;")
    e(f"    localparam OUTPUT  = 2'd3;")
    e()
    e(f"    reg [1:0] state;")
    e(f"    reg [{addr_bits_in}:0] in_count;")
    e(f"    reg [{addr_bits_out}:0] out_count;")
    e()

    # Input buffer
    e(f"    // Input buffer — holds all {n_in} inputs for the combinational core")
    for i in range(n_in):
        e(f"    reg signed [{bits-1}:0] in_buf_{i};")
    e()

    # Instantiate combinational core
    e(f"    // Combinational core — all weights hardwired")
    out_wires = []
    for i in range(n_out):
        wn = f"core_out_{i}"
        e(f"    wire signed [{bits-1}:0] {wn};")
        out_wires.append(wn)
    e()

    e(f"    {core_name} core (")
    conns = []
    idx = 0
    for inp_name in graph.input_names:
        shape = graph.input_shapes.get(inp_name, (1,))
        numel = 1
        for s in shape:
            numel *= s
        for i in range(numel):
            conns.append(f"        .{inp_name}_{i}(in_buf_{idx})")
            idx += 1
    for i in range(n_out):
        port_name = f"out_{i}"
        conns.append(f"        .{port_name}({out_wires[i]})")
    e(",\n".join(conns))
    e(f"    );")
    e()

    # Output mux
    e(f"    // Output multiplexer")
    e(f"    wire signed [{bits-1}:0] out_mux;")
    e(f"    assign out_mux =")
    for i in range(n_out):
        if i < n_out - 1:
            e(f"        (out_count == {addr_bits_out + 1}'d{i}) ? {out_wires[i]} :")
        else:
            e(f"        {out_wires[i]};")
    e()

    e(f"    assign ready = (state == IDLE);")
    e()

    # State machine
    e(f"    always @(posedge clk or negedge rst_n) begin")
    e(f"        if (!rst_n) begin")
    e(f"            state     <= IDLE;")
    e(f"            in_count  <= 0;")
    e(f"            out_count <= 0;")
    e(f"            out_valid <= 0;")
    e(f"            done      <= 0;")
    e(f"            data_out  <= 0;")
    e(f"        end else begin")
    e(f"            case (state)")
    e()
    e(f"                IDLE: begin")
    e(f"                    done      <= 0;")
    e(f"                    out_valid <= 0;")
    e(f"                    if (data_valid) begin")
    e(f"                        in_buf_0 <= data_in;")
    e(f"                        in_count <= 1;")
    e(f"                        state    <= LOADING;")
    e(f"                    end")
    e(f"                end")
    e()
    e(f"                LOADING: begin")
    e(f"                    if (data_valid) begin")
    e(f"                        case (in_count)")
    for i in range(1, n_in):
        e(f"                            {addr_bits_in + 1}'d{i}: in_buf_{i} <= data_in;")
    e(f"                        endcase")
    e(f"                        if (in_count == {addr_bits_in + 1}'d{n_in - 1}) begin")
    e(f"                            state <= COMPUTE;")
    e(f"                        end")
    e(f"                        in_count <= in_count + 1;")
    e(f"                    end")
    e(f"                end")
    e()
    e(f"                COMPUTE: begin")
    e(f"                    // Core is combinational — result is ready instantly")
    e(f"                    out_count <= 0;")
    e(f"                    data_out  <= out_mux;")
    e(f"                    out_valid <= 1;")
    e(f"                    state     <= OUTPUT;")
    e(f"                end")
    e()
    e(f"                OUTPUT: begin")
    e(f"                    data_out <= out_mux;")
    e(f"                    if (out_count == {addr_bits_out + 1}'d{n_out - 1}) begin")
    e(f"                        out_valid <= 0;")
    e(f"                        done      <= 1;")
    e(f"                        in_count  <= 0;")
    e(f"                        out_count <= 0;")
    e(f"                        state     <= IDLE;")
    e(f"                    end else begin")
    e(f"                        out_count <= out_count + 1;")
    e(f"                        out_valid <= 1;")
    e(f"                    end")
    e(f"                end")
    e()
    e(f"            endcase")
    e(f"        end")
    e(f"    end")
    e()
    e(f"endmodule")

    wpath = out / f"{wrapper_name}.v"
    wpath.write_text("\n".join(L), encoding="utf-8")
    return str(wpath)


def generate_tiny_tapeout_wrapper(
    graph: ComputeGraph,
    output_dir: str = ".",
) -> str:
    """
    Generate a Tiny Tapeout top-level wrapper.

    Tiny Tapeout interface:
        ui_in[7:0]   — dedicated inputs
        uo_out[7:0]  — dedicated outputs
        uio_in[7:0]  — bidirectional input
        uio_out[7:0] — bidirectional output
        uio_oe[7:0]  — bidirectional enable (1=output)
        ena          — always 1 when powered
        clk          — clock
        rst_n        — active-low reset
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    bits = graph.quant_config.bits
    name = f"tt_um_{graph.name}"

    L: List[str] = []

    def e(s=""):
        L.append(s)

    e(f"// {'=' * 75}")
    e(f"// {name} — Tiny Tapeout wrapper for {graph.name}")
    e(f"// Generated by weights2silicon (w2s)")
    e(f"//")
    e(f"// Protocol:")
    e(f"//   1. Assert rst_n low for one cycle to reset")
    e(f"//   2. Feed input bytes on ui_in with uio_in[0] (data_valid) high")
    e(f"//   3. Read output bytes from uo_out when uio_out[0] (out_valid) is high")
    e(f"//   4. uio_out[1] (done) goes high when all outputs sent")
    e(f"// {'=' * 75}")
    e()
    e(f"module {name} (")
    e(f"    input  wire [7:0] ui_in,")
    e(f"    output wire [7:0] uo_out,")
    e(f"    input  wire [7:0] uio_in,")
    e(f"    output wire [7:0] uio_out,")
    e(f"    output wire [7:0] uio_oe,")
    e(f"    input  wire       ena,")
    e(f"    input  wire       clk,")
    e(f"    input  wire       rst_n")
    e(f");")
    e()
    e(f"    // Bidirectional pins: [0]=data_valid input, rest unused")
    e(f"    assign uio_oe = 8'b0000_0011; // [1:0] are outputs")
    e()
    e(f"    wire [{bits-1}:0] serial_out;")
    e(f"    wire out_valid;")
    e(f"    wire done_sig;")
    e(f"    wire ready_sig;")
    e()
    e(f"    {graph.name}_serial serial_wrapper (")
    e(f"        .clk(clk),")
    e(f"        .rst_n(rst_n),")
    e(f"        .data_in(ui_in),")
    e(f"        .data_valid(uio_in[0]),")
    e(f"        .data_out(serial_out),")
    e(f"        .out_valid(out_valid),")
    e(f"        .done(done_sig),")
    e(f"        .ready(ready_sig)")
    e(f"    );")
    e()
    e(f"    assign uo_out = serial_out;")
    e(f"    assign uio_out[0] = out_valid;")
    e(f"    assign uio_out[1] = done_sig;")
    e(f"    assign uio_out[2] = ready_sig;")
    e(f"    assign uio_out[7:3] = 5'b0;")
    e()
    e(f"endmodule")

    wpath = out / f"{name}.v"
    wpath.write_text("\n".join(L), encoding="utf-8")
    return str(wpath)
